#' Transform Codes to Start-End Times
#' 
#' Transforms the range coding structure(s) from cm_time.temp (in list format) into a data frame of start and end times in long format.
#' 
#' @param \ldots list object(s) in the form generated by cm_time.temp
#' @param v.name sn optional name for the column created for the list.var argument
#' @param list.var logical.  If TRUE creates a column for the data frame created by each time.list passed to cm_t2l
#' @param star.end logical. If TRUE outputs stop and end times for each cm_time.temp list object
#' @return Generates a data frame of start and end times for each code.
#' @seealso 
#' \code{\link{cm2long}}
#' \code{\link{cm_time.temp}}
#' @references Miles, M. B. & Huberman, A. M. (1994). An expanded sourcebook: Qualitative   data analysis. 2nd ed. Thousand Oaks, CA: SAGE Publications.
#' @keywords coding, time span
#' @examples
#' x <- list(
#'     transcript_time_span = qcv(00:00 - 1:12:00),
#'     A = qcv(2.40:3.00, 5.01, 6.62:7.00, 9.00),
#'     B = qcv(terms = "2.40, 3.01:3.02, 5.01, 6.62:7.00, 9.00, 1.12.00:1.19.01"),
#'     C = qcv(2.40:3.00, 5.01, 6.62:7.00, 9.00, 17.01)
#' )
#' dat <- cm_time2long(x)
#' gantt_wrap(dat, "code", border.color = "black", border.size = .75)
cm_time2long <-
function(..., v.name = "variable", list.var = TRUE, 
    start.end = FALSE){
    mf <- match.call(expand.dots = FALSE)
    objs <- as.character(mf[[2]])
    L1 <- lapply(objs, get)
    names(L1) <- objs
    L2 <- lapply(L1, cm_t2l, list.var = FALSE, start.end = start.end)
    if (list.var) {
        L2 <- lapply(seq_along(L2), function(i) data.frame(L2[[i]], 
            VAR = objs[i]))
    }
    DF <- data.frame(do.call(rbind, L2), row.names = NULL)
    if (list.var) {
        colnames(DF)[ncol(DF)] <- v.name
    }
    DF
}
